-- Adds the three difficulty-calibrated dot-set columns generated by the
-- Python worker.  NULL means "not yet generated"; the Flutter client falls
-- back to the editor `dots` column via Project.dotsForLevel() until the
-- worker re-processes the project.

ALTER TABLE projects ADD COLUMN IF NOT EXISTS dots_easy   JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS dots_medium JSONB;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS dots_hard   JSONB;
